[package]
name = "untitled1"
version = "0.1.0"
edition = "2021"

[dependencies]
headless_chrome = {git = "https://github.com/rust-headless-chrome/rust-headless-chrome", features = ["fetch"]}
reqwest = "0.9.24"
serde_json = "1.0.124"